export const employeesData = [
  {
    id: 1,
    firstName: "Susan",
    lastName: "Jordon",
    email: "susan@example.com",
    department: "Cyberteq",
    role: "UI/UX",
    date: "2019-04-11",
  },
  {
    id: 2,
    firstName: "Adrienne",
    lastName: "Doak",
    email: "adrienne@example.com",
    department: "SOC",
    role: "Project Manager",
    date: "2019-04-17",
  },
  {
    id: 3,
    firstName: "Rolf",
    lastName: "Hegdal",
    email: "rolf@example.com",
    department: "Falcon",
    role: "UI/UX",
    date: "2019-05-01",
  },
  {
    id: 4,
    firstName: "Kent",
    lastName: "Rosner",
    email: "kent@example.com",
    department: "InfoSec",
    role: "Software Engineer",
    date: "2019-05-03",
  },
  {
    id: 5,
    firstName: "Arsenio",
    lastName: "Grant",
    email: "arsenio@example.com",
    department: "Cyberteq",
    role: "Administrator",
    date: "2019-06-13",
  },
  {
    id: 6,
    firstName: "Laurena",
    lastName: "Lurie",
    email: "laurena@example.com",
    department: "Cyberteq",
    role: "UX Engineer",
    date: "2019-07-30",
  },
  {
    id: 7,
    firstName: "George",
    lastName: "Tallman",
    email: "george@example.com",
    department: "Falcon",
    role: "Backend developer",
    date: "2019-08-15",
  },
  {
    id: 8,
    firstName: "Jesica",
    lastName: "Watlington",
    email: "jesica@example.com",
    department: "InfoSec",
    role: "UI/UX",
    date: "2019-10-10",
  },
  {
    id: 9,
    firstName: "Matthew",
    lastName: "Warren",
    email: "matthew@example.com",
    department: "Falcon",
    role: "Graphic Designer",
    date: "2019-10-15",
  },
  {
    id: 10,
    firstName: "Lyndsey",
    lastName: "Follette",
    email: "lyndsey@example.com",
    department: "Cyberteq",
    role: "UI/UX Developer",
    date: "2020-01-15",
  },
];

export const leavesData = [
  {
    id: 1,
    employeeName: "Joseph Boyce",
    leaveType: "Annual Leave",
    startDate: "2020-01-23",
    endDate: "2020-01-30",
    status: "Pending",
  },
  {
    id: 2,
    employeeName: "William Jill",
    leaveType: "Emergency Leave",
    startDate: "2020-01-23",
    endDate: "2020-01-30",
    status: "Approved",
  },
  {
    id: 3,
    employeeName: "Joseph Boyce",
    leaveType: "Annual Leave",
    startDate: "2020-01-23",
    endDate: "2020-01-30",
    status: "Declined",
  },
  {
    id: 4,
    employeeName: "Adjetey Marie",
    leaveType: "Maternity Leave",
    startDate: "2020-01-23",
    endDate: "2020-01-30",
    status: "Pending",
  },
  {
    id: 5,
    employeeName: "John Smith",
    leaveType: "Sick Leave",
    startDate: "2020-01-23",
    endDate: "2020-01-30",
    status: "Approved",
  },
];
